### ISSUE TITLE
Discovery stopped working since v8.3

### ISSUE THREAD

**Issue by ChaosCom** [Pupix/rift-explorer#10]
Looks like the exploration stopped working with the release of client v 8.3. Could you have a look into this?

**Comment by Pupix** [comment]
You may have an older version. The one I got works fine.

![image](https://user-images.githubusercontent.com/4929965/35993199-da4117b0-0d0c-11e8-8c5f-1690b0536fb2.png)

Head over to [releases](https://github.com/Pupix/rift-explorer/releases) and try the latest version.

**Comment by ChaosCom** [comment]
You were right, it was an older version that stopped working; the newer version works. Thanks for the quick response.
