### ISSUE TITLE
icon wont change

### ISSUE THREAD

**Issue by coffeemixer32** [Pupix/rift-explorer#101]
the "keep changing it, it will stick eventually" thing doesnt really seem to be changing anything for me. Have kept on trying  to change it, so it changes in lobby but not in top right corner, went ingame, and out. where it then reverts to old one, and same thing if I  try to relog and do it. 
so is it a "do it 50 times and it will stick" or is it just an issue in general?, have done it on alot of accs on first try, but now I just cant anymore

**Comment by RayZz-** [comment]
Duplicate of #45
