### ISSUE TITLE
rift explorer doesn't work?

### ISSUE THREAD

**Issue by arthures11** [Pupix/rift-explorer#102]
Does it work anymore? I can't do anything with it.

**Comment by RayZz-** [comment]
Not really helpful, saying you can't do anything with it gives no valuable information to help assist in fixing the issue.

**Comment by wzpyh** [comment]
the play button is disabled if starting the game with rift explorer , it just happened after today's update.

**Comment by arthures11** [comment]
I think it doesn’t swap back to the proper version of old client that’s why it’s buggy.

**Comment by RayZz-** [comment]
I'll take a loon into it at later the evening.

**Comment by RayZz-** [comment]
As for now can you guys please try running from source.

**Comment by RayZz-** [comment]
Can you guys try running the new release.

**Comment by arthures11** [comment]
> Can you guys try running the new release.

working as supposed, thank you!

**Comment by RayZz-** [comment]
Glad to help, on that note I'll close this issue.
