### ISSUE TITLE
Stuck on waiting for League to start

### ISSUE THREAD

**Issue by Achieve-Glory** [Pupix/rift-explorer#104]
I have swagger enabled, rift explorer does not detect that the client is running

**Comment by RayZz-** [comment]
How was swagger enabled and also what OS and region.

**Comment by Achieve-Glory** [comment]
> How was swagger enabled and also what OS and region.

Swagger was enabled by putting enable_swagger: true in the system.yaml file, windows 10 NA

**Comment by RayZz-** [comment]
That is no longer required as rift-explorer does this for you now and has done for quite a while now.

**Comment by Achieve-Glory** [comment]
Rift explorer still gets stuck on waiting for league to start even if I remove that line from the system.yaml file. I open rift explorer, then I open league with administrator privileges, is there something I'm doing wrong?

**Comment by Achieve-Glory** [comment]
it just initiated a full repair of my client, and it keeps getting stuck in a loop of rift explorer needs to restart your client to work properly

**Comment by RayZz-** [comment]
Are you using the latest version?

**Comment by Achieve-Glory** [comment]
Yes, looks like it is working now after repairing my client a few times

**Comment by RayZz-** [comment]
Alright I'm going to close this issue in that case.
