### ISSUE TITLE
Lagged

### ISSUE THREAD

**Issue by arthures11** [Pupix/rift-explorer#107]
It's very lagged once it finally "connects"/fetch account data. Literally need to wait few minutes for 1 click or it will stuck forever.

**Comment by RayZz-** [comment]
Could this perhaps be a result of your hardware instead of rift-explorer?

**Comment by arthures11** [comment]
I don't think so, i7-8750h+1660ti 16gb ram

**Comment by ArtBlnd** [comment]
Same issue here.

**Comment by ArtBlnd** [comment]
scrolling with mouse wheel works, but not with scrolling bar. interacting with another things does not work. it just freezed.

**Comment by ArtBlnd** [comment]
wired thing is, when I dumped its process. it just works fine

**Comment by Hi-Ray** [comment]
Planned fix 7.0.0
