### ISSUE TITLE
Question: Is there any information about api?

### ISSUE THREAD

**Issue by DjordjeMandic** [Pupix/rift-explorer#11]
There is model Schema but fopr example in notifications
```
PlayerNotificationResource {
backgroundUrl (string, optional),
created (string, optional),
critical (boolean, optional),
data (object, optional),
detailKey (string, optional),
dismissible (boolean, optional),
expires (string, optional),
iconUrl (string, optional),
id (integer, optional),
source (string, optional),
state (string, optional),
titleKey (string, optional),
type (string, optional)
}
```

How do i know what titleKey is, i know for club_invite but how can i find out other types? Example club_join or something else, to make my own custom notifications?
I get this: 
![image](https://user-images.githubusercontent.com/6750655/36408974-ece694bc-1608-11e8-9e4d-4cd0617dbef8.png)
How can i make custom title and message?
Is there full documentation like classic riot api?

**Comment by Pupix** [comment]
Not that I know of. What you see there are the official RIOT docs that ship with the LCU.
A PR with a more exhaustive documentation is always welcome.
