### ISSUE TITLE
Can't change profile info

### ISSUE THREAD

**Issue by xplook** [Pupix/rift-explorer#110]
So I'm trying to change the border/ rank but I'm not able to.
I just can change the background and icon.
Any help?

**Comment by lenghiadz1** [comment]
How to change icons
I don't know how to use the code
{
  "inventoryToken": "string",
  "profileIconId": 0
}

**Comment by Hi-Ray** [comment]
As stated above it is not related to the software therefore will not be answered, rift-explorer is to provide documentation for the LCU api.
