### ISSUE TITLE
Can Rift Explorer be applied to Chinese Tencent League server?

### ISSUE THREAD

**Issue by SaeronMeng** [Pupix/rift-explorer#114]
I'm a Chinese developer and intend to build toolkits for League of Legends of Chinese version. However after running Rift Explorer (I tried both prebuilt version and building from source) and LOL clients, the former was always saying "Waiting for League to start...". So I wonder whether I am eligible to use League Client API and whether there is something wrong with my steps. Thanks!

More details: When building from source I encountered this:
`Error: Could not connect
    at Socket.onerror (C:\Users\40471\rift-explorer\node_modules\discord-rpc\src\transports\ipc.js:32:16)
    at Object.onceWrapper (events.js:288:20)
    at Socket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)`
So I adopted your solution mentioned in issue[#88 ]. Even though the error disappeared, Rift Explorer still could not detect my league client.

**Comment by RayZz-** [comment]
We plan on fixing most issues in a new version soon(tm)

**Comment by Hi-Ray** [comment]
wew that was a long soontm almost Riot Games time but this should be fixed in the new Rift Explorer 7 coming soon.

**Comment by Hi-Ray** [comment]
https://github.com/HextechDocs/lcu-explorer

**Comment by Kiswelrg** [comment]
may i ask does LCU api work for chinese LOL. coz as far as i know, Tencent doesn't seem to be allowing api like stuff in its games.
