### ISSUE TITLE
issues with new client

### ISSUE THREAD

**Issue by erich0864** [Pupix/rift-explorer#115]
I can't get it to work when using the New client, and it opens the old client but then it cannot load my friends list or show my icon/lvl

**Comment by hugogomess** [comment]
I'm updating connection with new client

**Comment by moreal** [comment]
Hello @hugogomess , Are there more updates about this issue?
When I worked with service accessed with information got from lcu-connector, it responded `RESOURCE_NOT_FOUND` at `/swagger/v2/swagger.json` endpoint.
Does it seem related to this issue?

**Comment by Thyoity** [comment]
Any update on this issue? I'm having the same problem.

**Comment by hugogomess** [comment]
I ran out of time to finish it, but if you try to open it a few times you can use it normally

**Comment by diablopk** [comment]
Try to open a few times the client or the explorer?

**Comment by hugogomess** [comment]
The client, restart a few times

**Comment by diablopk** [comment]
Will try! Thx buddy!

**Comment by stefanvuckovic11** [comment]
same issue! Restarting the client doesn't help

**Comment by kos-dekkal** [comment]
I've restarted client more than 20 times and it still asking even though I haven't even logged in yet

**Comment by Hi-Ray** [comment]
This should be resolved in Rift Explorer 7 which is coming soon.

**Comment by Hi-Ray** [comment]
https://github.com/HextechDocs/lcu-explorer
