### ISSUE TITLE
Unable to restart League correctly (Garena)

### ISSUE THREAD

**Issue by lowyiyiu** [Pupix/rift-explorer#116]
1. Rift Explorer run as administrator
2. Launch League via Garena
3. Rift Explorer needed to restart League
4. League restarted without Garena's arguments (presumably, since League was launch and required login)
5. Rift Explorer detected League and start fetching resources list
6. League crashed and closed
7. Rift Explorer waits for League to start

**Comment by anwinkushal** [comment]
it works in old ver 5.0

**Comment by Hi-Ray** [comment]
Planned fix 7.0.0
