### ISSUE TITLE
How to use client WebSocket 

### ISSUE THREAD

**Issue by stirante** [Pupix/rift-explorer#13]
I found, that client uses WebSocket to publish some events which list is in /Help endpoint. Also I think it uses wamp-proto.org as I found some references to that in code (plugin-runner/loader.js). 

Does anyone knows how to use those events?

**Comment by Pupix** [comment]
Hello!

Yes, the client uses WAMP 1.0, unfortunately this doesn't have it integrated as the core of the swagger UI (which this is based on) doesn't support WebSockets AFAIK.
(I've posted in the past)[https://gist.github.com/Pupix/eb662b1b784bb704a1390643738a8c15] a node.js implementation of mine of the WAMP protocol for the LCU.

Cheers
