### ISSUE TITLE
help

### ISSUE THREAD

**Issue by LanzTokisaki** [Pupix/rift-explorer#130]
is there a way to get the current game time?

**Comment by BakaFT** [comment]
There is something that can give you the unixtime when the LeagueClient starts in RESTful apis, but I forgot it's name. And you can find the timer of a game with the[ Live Client Data API](https://developer.riotgames.com/docs/lol#game-client-api_live-client-data-api).
It's your matter to find out what the APIs do, not rift-explorer.

**Comment by Hi-Ray** [comment]
The LCU API which rift-explorer provides documentation for is not aware about anything the game itself aside from being ingame and what champion you are playing.
