### ISSUE TITLE
Not working on the PBE

### ISSUE THREAD

**Issue by artem1919** [Pupix/rift-explorer#14]
On launch: https://i.imgur.com/3WRAeJO.png
After pressing OK: https://i.imgur.com/VxzFxph.png

Edit: Neither on the live client now

**Comment by Pupix** [comment]
This change hit the live client these days too and it seem like it's here to stay. Before this update (8.14) Rift Explorer relied on a swagger file that came with the LCU to work, however now that file seems to be gone.

I will be looking into it more this week/weekend to see if I can resurrect the removed file.

**Comment by artem1919** [comment]
These files aren't really needed as you can simply launch the 8.13 client with the --disable-patching flag

**Comment by Pupix** [comment]
![image](https://user-images.githubusercontent.com/4929965/43104083-7554e4bc-8ed0-11e8-8088-9b64790d4aae.png)

Just a few more days.

**Comment by Pupix** [comment]
[v2.0.0](https://github.com/Pupix/rift-explorer/releases/tag/v2.0.0) has been released with a fix for this.

Cheers everybody

**Comment by pipe01** [comment]
Awesome, thanks!
