### ISSUE TITLE
Prebuild 7.0.0?

### ISSUE THREAD

**Issue by zaryar** [Pupix/rift-explorer#146]
Do you plan to prebuild the 7.0.0 version for windows?

**Comment by Hi-Ray** [comment]
I'm planning on it however due to IRL issues I have had to delay it sorry about that.

**Comment by zaryar** [comment]
Thank you, I love your work :)

**Comment by Hi-Ray** [comment]
Hi try using the current branch of 7.0.0 if it works we plan on releasing it soon

**Comment by Hi-Ray** [comment]
https://github.com/HextechDocs/lcu-explorer
