### ISSUE TITLE
Body parameter seems to be broken

### ISSUE THREAD

**Issue by artem1919** [Pupix/rift-explorer#16]
Whenever there's some endpoint requiring a body parameter, the API Explorer seems to treat it as a header.
In addition to that, the model schema shows nothing, and it doesn't use a textarea. Both are probably a result of the header treatment.

This is how it looks like in the current version: https://i.imgur.com/4B6krRr.png
This is how it used to look like in the old version: https://i.imgur.com/v19uJME.png

**Comment by Pupix** [comment]
There doesn't seem to be anything that allows me to identify where the parameter should end up as far as I see with the new approach. I am looking at the `/help` endpoint trying to find differences but so far there's none 😞

**Comment by Pupix** [comment]
For now the header fields are statically excluded. If new ones come about in the future it may brake but for now it's the best I can do.

[New version here](https://github.com/Pupix/rift-explorer/releases/tag/v2.0.1)
