### ISSUE TITLE
Body parameter ignored in most of post requests?

### ISSUE THREAD

**Issue by DjordjeMandic** [Pupix/rift-explorer#18]
Curl:
```
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'Authorization: Basic hidden' -d 'test123' 'https://127.0.0.1:hidden/lol-game-client-chat/v1/instant-messages'
```

Request Headers:
```
{
  "Accept": "application/json"
}
```
Response Body:
```
{
  "errorCode": "RPC_ERROR",
  "httpStatus": 400,
  "implementationDetails": {},
  "message": "A value for 'summonerName' is required."
}
```
Response Code:
```
400
```
Response Headers:
```
{
  "status": "400",
  "access-control-expose-headers": "content-length",
  "cache-control": "no-store",
  "access-control-allow-origin": "https://127.0.0.1:hidden",
  "content-length": "151",
  "vary": "origin",
  "content-type": "application/json"
}
```

I did enter username but its like i didnt. Is it app bug?

![image](https://user-images.githubusercontent.com/6750655/44515906-fa1f7800-a6c3-11e8-8b76-4c8f5b02d2c1.png)

**Comment by DjordjeMandic** [comment]
I also found out that message value param is ignored in POST /lol-game-client-chat/v1/party-messages.

**Comment by Pupix** [comment]
Hmmm. Yes, some calls seem to be broken. I may have to make a guide on how to enable swagger from the LCU client itself without trying to build the file dynamically because the `/help` endpoint doesn't seem to have all the data necessary to rebuild the whole thing.
Will look at it this weekend.

**Comment by Pupix** [comment]
Sorry about the delay, I've been in vacantion 🍹 .
A [new version](https://github.com/Pupix/rift-explorer/releases/tag/v3.0.0) has been added that fixes all of the request related problems.

Cheers,
Pupix.
