### ISSUE TITLE
How to get the current summoner skins?

### ISSUE THREAD

**Issue by Thyoity** [Pupix/rift-explorer#19]
Is there an API to get the current logged in account skins?

Theoretically this endpoint should exist, because the client has this feature now, am I right?
I could'nt find this in Rift Explorer, maybe I didn't dig enough.

Anyone?

**Comment by Pupix** [comment]
Hello!
The endpoint is `GET /lol-inventory/v1/inventory`. You need to pass the inventoryTypes `["CHAMPION_SKIN"]` to find the skins.

Cheers,
Pupix

**Comment by Thyoity** [comment]
Oh wow! Sorry for the late response.

Awesome work!! Thanks Pupix!
