### ISSUE TITLE
Downloading Replay

### ISSUE THREAD

**Issue by blackjack4494** [Pupix/rift-explorer#20]
The POST is broken. No contextData will be sent. There still seem some other endpoints do not function properly as well. I need to send posts etc. externally and not within rift explorer.

**Comment by Pupix** [comment]
Strange. All call should work properly. Which endpoint are you using?

**Comment by blackjack4494** [comment]
`/lol-replays/v1/rofls/{gameId}/download`
`/lol-replays/v1/rofls/{gameId}/download/graceful`

Both do not work for me in Rift Explorer. But I can use them in my python and javascript code. And they do work there. I noticed a few other POST endpoints do not work as well. I had several problems with spectate endpoints. Those are the ones I mainly use.

**Comment by blackjack4494** [comment]
I indeed use a metadata check before also in my script. But I tried sending a request without contentType in Rift and in Script. And I dunno why but when I leave it out it won't download properly at least with download. When I use download/graceful I can send a request without contentType. 
I tried it with Rift 2.0.1 and 3. I am having two scripts javascript for production use and python for testing. In python I use curl and in addition another framework as alternative.

**Comment by inferior481** [comment]
I try to use a metadata before download in both postman and my Go code, but it shows 400:"A value for 'contextData' is required." Is there anything wrong?

GET "https://127.0.0.1:3918/lol-replays/v1/metadata/1906151169"
POST "https://127.0.0.1:3918/lol-replays/v1/rofls/1905966546/download"
