### ISSUE TITLE
Can't load Swagger. Make sure it's enabled in system.yaml

### ISSUE THREAD

**Issue by JohnnyDeeee** [Pupix/rift-explorer#25]
The app can't access the swagger documentation..

I have enabled swagger by editting my `system.yaml`

```
---
enable_swagger: true
app:
  app_name: LeagueClient
...
```

The app receives a 404 on the url it is trying to access.
Is there some documentation on what the url should be or a way to validate that the swagger json is actually present?

This is the url it is trying to access: 
```
https://riot:REDACTED@127.0.0.1:23558/swagger/v2/swagger.json
```

(the app is running with administrator privileges)

**Comment by Pupix** [comment]
The link you posted is correct, if you go there you should see a JSON document like this one https://gist.github.com/Pupix/1078c64c9bc33809eccfd60556411679

**Comment by Pupix** [comment]
This has been patched in the latest release. The patching is done automatically now.
