### ISSUE TITLE
How do I fix this

### ISSUE THREAD

**Issue by Ribathics** [Pupix/rift-explorer#26]
I know this sort of question might be very basic, but I've already searched and tried many things and can't still fix this error.
Whenever I try to open the app on rift explorer this pops up:
![screenshot_46](https://user-images.githubusercontent.com/46284117/50564726-ac201e00-0d0e-11e9-8c54-c767e068c7d5.png)
I just don't know what to do. Also, I've already done the enable_swagger: true
Since it's in portuguese, I'll try to roughly translate it:
Line: 1
Charact.: 1
Error: Syntax error
Code: 800A03EA
Origin: Microsoft JScript compilation error

**Comment by Pupix** [comment]
No idea. What OS are you using?

**Comment by Zylviij** [comment]
It appears that `app.js` wasn't opened with node but with Microsoft's JScript. 

Electron does not come close to supporting JScript. Install node and you may have better luck.
For me, the prebuilt binaries worked fantastically.

**Comment by Pupix** [comment]
So it's a non issue. Just use the prebuilt version https://github.com/Pupix/rift-explorer/releases/tag/v3.0.0
