### ISSUE TITLE
The application can't run in your PC

### ISSUE THREAD

**Issue by Rosas1** [Pupix/rift-explorer#29]
Everytime I open the Riftexplorer.exe Windows(10) says that this application can't be executed in my PC and to find a version that run talking to the software owner.

**Comment by Pupix** [comment]
Wouldn't know. First time hearing about this. Got a screenshot?

**Comment by Rosas1** [comment]
(It's in portuguese because i'm from Brazil)
http://prntscr.com/mv9thl
English:
"This application can not run on your PC
To locate a version for your PC, consult your software vendor."

**Comment by Pupix** [comment]
After looking around it seems to be a local configuration stopping the program from running, I can't do anything about that. Google the error message and a bunch of solutions will pop up.
