### ISSUE TITLE
Trouble finding the client. Make sure your League is running.

### ISSUE THREAD

**Issue by Virace** [Pupix/rift-explorer#3]
zh_CN

![](https://ws1.sinaimg.cn/large/a1e6bd2bly1fm1gptddqmj217q0ondga.jpg)
![](https://ws1.sinaimg.cn/large/a1e6bd2bly1fm1gsbh9fvj20po02rgm4.jpg)

**Comment by Pupix** [comment]
Need more info on this. Is there a custom launcher running for league or the plain LeagueUX.exe?

Could you post your process list with the running arguments visible?

**Comment by be90728** [comment]
也許你可以開啟cmd後 cd到LeagueClient資料夾 運行 "LeagueClient.exe --no-rads" (不含雙引號)(開啟後請不要點選任何確認按鈕)，並且開啟Swagger 也許這樣就可以了(我是台灣Garena地區，有反作弊，會無法偵測到LeagueClient)

**Comment by Virace** [comment]
@be90728 大陆的是有单独的的登录器的，就像泰服。所以直接启动LeagueClient.exe 是无法登陆游戏的。

**Comment by be90728** [comment]
@Virace 我知道 我們台服也是 因為這種機制 你沒辦法使用Swagger直接發送API 需要使用網頁POST、GET工具才可以使用 你不需要登錄 只要讓程式抓得到你的遊戲進程即可

**Comment by be90728** [comment]
@Virace 抓到進程以後 就可以把遊戲關掉(啟動Swagger的CMD跟Swagger不要關掉)，然後使用正規登陸器登陸~

**Comment by Virace** [comment]
@be90728  OK ，我懂你意思。非常感谢~

**Comment by be90728** [comment]
用Swagger主要是看他的API網址、POST的格式(大部分都是json)
而且還可以自訂訊息在遊戲客戶端中顯示喔~

**Comment by Virace** [comment]
@be90728 了解了 :)

**Comment by Virace** [comment]
@Pupix

![](https://ws1.sinaimg.cn/large/a1e6bd2bly1fm2naw0i57j20tg099aat.jpg)
![](https://ws1.sinaimg.cn/large/a1e6bd2bly1fm2naw7y6rj20uu09v76k.jpg)

**Comment by be90728** [comment]
這樣子就可以開啟Swagger了 我這邊有個文件 你可以搜尋你想要的
[LoLAll.txt](https://github.com/Pupix/rift-explorer/files/1523753/LoLAll.txt)

**Comment by Pupix** [comment]
@Virace can you try running it as admin? The .exe should have been found but seems to fail for some reason.

**Comment by Virace** [comment]
@Pupix This game has extra launcher in China!!   "Rift Explorer.exe" is run by the admin

**Comment by Pupix** [comment]
Doesn't matter if there's an extra launcher. The program is looking for the `LeagueClientUx.exe` file not anything else. @be90728 seem to have gotten it working and he may be chinese too.

**Comment by be90728** [comment]
@Pupix I'm Taiwan :))

**Comment by be90728** [comment]
@Virace 你加我QQ吧 我幫你3328154983

**Comment by Pupix** [comment]
@Virace after some testing I noticed that Garena elevates (makes them run as admin) the league processes. If you run rift-explorer as admin too it should work. Can you try that and let me know?

**Comment by be90728** [comment]
@Pupix They are Tencent, I am Garena, Tencent is China, Garena is Taiwan
Tested and successfully found LeagueClient at Garena

**Comment by Pupix** [comment]
I tested the Tencent client too, there's no problem there. Once you pick your server (I picked one with the old Baron Nashor icon) it will find the client.

**Comment by Pupix** [comment]
Closed due to inactivity

**Comment by BastienVerschaete** [comment]
@Pupix sorry for bothering you on this still, but in Europe with EUW client, Rift Explorer doesn't seem to find my game (both ran as administrator) I have checked the processes and LeagueClientUx.exe is running
