### ISSUE TITLE
enable_swagger causes loop

### ISSUE THREAD

**Issue by ChaosCom** [Pupix/rift-explorer#34]
For a few days (most likely since the new patcher from the 18.04.2019, https://support.riotgames.com/hc/en-us/articles/360015621174) exploration of the API via swagger doesn't work anymore:

Rift Explorer detects that a necessary entry is missing (enable_swagger: true in system.yaml), closes the client, auto-updates said file and waits for the league client to restart. 
The league launcher itself detects the change, removes it, and automatically restarts itself after 10 seconds. 

Rinse and repeat.
Can you confirm this behavior, @Pupix ?
Does this also mean that the days of API exploration have come to an end ?

**Comment by Pupix** [comment]
Yea, I just tested it and can confirm it. Using the old patcher it works just fine, but it breaks with the new one.

It's not much I can do about it since this is on Riot's end. I'll ask around and see if it's intentional or not and if there's any workarounds.

**Comment by ChaosCom** [comment]
Any pointers of how to force use of the old patcher ? The new patcher is causing all kinds of issues, and is very aggressive when it comes to reverting changes -- even simple links / shortcuts that you create in the league folder get removed by it... 

Btw, any intention of making the Rift Explorer accept a Swagger.json file instead of pulling it from the process ? That way navigating (older) versions of the Swagger API would become possible.

**Comment by Pupix** [comment]
Don't know if you can revert back. To enable it tho I had to edit `C:\Riot Games\League of Legends\Config\LeagueClientSettings.yaml` and set `toggles` to 0. Try setting it to a big number, IIRC it's the timestamp diff between current date and the date your client will start using the new patcher. 

```yaml
install:
    ...
    patcher:
        ...
        toggles:
            new_client_patcher: 0
            new_game_patcher: 0
    ...
```

You could also try a bunch of flags like `--disable-self-update` to see if it stops the client from repairing itself 🤷‍♂️

**Comment by ChaosCom** [comment]
That actually seems to have worked. 

Changing those 2 entries to "values in the future" resulted in a cascade of other values in LeagueClientSettings.yaml changing, the repair function to get triggered (from what I can tell this actually re-downloads the (old) client archive files to <LeagueFolder>\RADS\temp\patching, so it can take a while) and then using the old files from then on.

After that, enable_swagger doesn't get reverted anymore, and the other annoyances seem to have vanished as well. Thanks a bunch!

**Comment by Morilli** [comment]
Would suggest re-opening this because eventually the new client patcher will be enforced and this issue will be unavoidable.

**Comment by Pupix** [comment]
I linked the Rito issue instead of reopening this one. You can follow it there.

**Comment by Dracobark** [comment]
Workaround works for me too, is there any way to export the docs so they can be preserved?

**Comment by thickmacroni** [comment]
> That actually seems to have worked.
> 
> Changing those 2 entries to "values in the future" resulted in a cascade of other values in LeagueClientSettings.yaml changing, the repair function to get triggered (from what I can tell this actually re-downloads the (old) client archive files to \RADS\temp\patching, so it can take a while) and then using the old files from then on.
> 
> After that, enable_swagger doesn't get reverted anymore, and the other annoyances seem to have vanished as well. Thanks a bunch!

I'm new in this settings are and I am not quite sure what you exactly did D: can you explain it a bit more for me?

**Comment by thickmacroni** [comment]
Is there any method to get the old patcher back? I didn't know there is a new Patcher around and so I reinstalled League of Legends some days ago cuz of some Issues. Now I have the new Patcher and can't go back to the old one because it is deleted.

**Comment by Pupix** [comment]
It's like 3 comments above. https://github.com/Pupix/rift-explorer/issues/34#issuecomment-485089457

**Comment by DXYZRK** [comment]
I am literally lost. I can't figure out what I've got to do. My `toggle` is already set on `0`when I go into the file. I've tried to put it on a big number. It didn't help. And where do I have to put the `--disable-self-update```? Are there more steps I've got to do to get Rift Explorer started again?

**Comment by ezx223** [comment]
Yea same problem, I'm so lost and I've heard this bypass is not working either is it right @Pupix

**Comment by Pupix** [comment]
If that bypass doesn't work for you there's no much I can do right now. As stated by Riot in https://github.com/RiotGames/developer-relations/issues/117 , they do not provide support for the API Rift Explorer is using. Best you can do is show support for the issue so they may change their stance if enough developers want this to be supported.

**Comment by Jeymej** [comment]
I have swagger enabled in system.yaml and both new_client_patcher: 0 and the new_game_patcher: 0 set like that by default. Yet so, it still says it cannot load swagger and eventually it keeps repairing it self after the api has been enabled...

**Comment by Pupix** [comment]
This has been solved with the latest release https://github.com/Pupix/rift-explorer/releases/tag/v6.0.1
