### ISSUE TITLE
the icon problem

### ISSUE THREAD

**Issue by derekho69** [Pupix/rift-explorer#35]
so this [https://imgur.com/a/WioKgfL](account) doesn't have those  new account icons like ahri,mf or something,don't have the bug that last time I linked,is it related to account and old account or just a random bug

**Comment by Pupix** [comment]
How's this related to Rift Explorer?

**Comment by derekho69** [comment]
i mean this account doesn't affected by the rift explorer icon bug that automatically change the icon,just asking if it's related
