### ISSUE TITLE
system.yawl and patching/updating problem

### ISSUE THREAD

**Issue by okaaaaaay** [Pupix/rift-explorer#36]
Okay so I edited system.yawl file like this:
---
enable_swagger: true
app:
  app_name: LeagueClient
...

But whenever I try to start league, no matter how, as an administrator or not, it's constantly repairing itself and through that repair it removes 'enable_swagger: true' from system.yawl

Is there anything I can do to stop that repair from happening?

It's happening ONLY when I mess with system.yawl file.

Also if I try it without enable_swagger: true it just restarts client without any results, it's just updating over and over again and whenever client starts it says "Rift Explorer needs to restart the League Client to enable the API documentation"

There's also 'API has been auto-enabled. Please restart the League Client' message, and if I restart client then it just does the same thing over and over again.

**Comment by Pupix** [comment]
This is a known problem with the new patcher. https://github.com/RiotGames/developer-relations/issues/117
You can disable it in the meantime.

**Comment by AKC0412** [comment]
hey pupix i was wondering if i can add some rp on my account badly needed just for me hahahaha

**Comment by Pupix** [comment]
lmao. no.

**Comment by Pupix** [comment]
This has been fixed in [v6.0.0](https://github.com/Pupix/rift-explorer/releases/tag/v6.0.0). Try it out and let me know if it's working for you.

**Comment by AKC0412** [comment]
i tried editing response body using fiddler and burpsuite i knwow their sites password and ican access just the url

**Comment by AKC0412** [comment]
thanks pupix ill let you know when i hacked it is there anymore i can change beside the icons
