### ISSUE TITLE
Waiting for League to start.

### ISSUE THREAD

**Issue by ezx223** [Pupix/rift-explorer#37]
EUW server worked fine for a while, today not sure what's wrong tried everything I can is there a straight solution to this?

**Comment by Pupix** [comment]
what's even the problem?

**Comment by ezx223** [comment]
![Screenshot_19](https://user-images.githubusercontent.com/50252063/57261397-ebb59880-7067-11e9-82fd-38dcfbb6b56b.png)
Tried opening both with admin not working

**Comment by Pupix** [comment]
Can you run `WMIC PROCESS WHERE "name='LeagueClientUx.exe'" GET commandline` in a powershell and post the result here?

**Comment by ezx223** [comment]
![Screenshot_20](https://user-images.githubusercontent.com/50252063/57299072-387a8d00-70c3-11e9-9895-cab9ff446c86.png)

**Comment by Pupix** [comment]
It only says that when League is not running. 🤔

**Comment by ezx223** [comment]
D:/Riot/RADS/projects/league_client/releases/0.0.0.191/deploy/LeagueClientUx.exe "--release=0.0.0.160" "--rads-product-directory=D:/Riot/RADS/solutions/league_client_sln/releases/0.0.0.160/deploy/" "--remoting-auth-token=kqgGgQ3JRCAbmq61dL7VFA" "--respawn-command=LeagueClient.exe" "--respawn-display-name=League of Legends" "--app-port=59682" "--install-directory=D:/Riot/" "--app-name=LeagueClient" "--ux-name=LeagueClientUx" "--ux-helper-name=LeagueClientUxHelper" "--log-dir=LeagueClient Logs" "--bugsplat-name=league_client_riotgames_com" "--bugsplat-platform-id=EUW1" "--app-log-file-path=D:/Riot/Logs/LeagueClient Logs/2019-05-07T16-18-33_11816_LeagueClient.log" "--app-pid=11816" "--no-proxy-server"

**Comment by someone32** [comment]
I'm having the same issue, and my friend, with the same IP is not, I compared command lines and they had nothing different except the auth token/port/log/pid, all the rest was exactly the same.

**Comment by Pupix** [comment]
@someone32 is your League installed on a different drive too? That's the only discriminant I see.

@ezx223 Try moving Rift Explorer onto your D drive and run it from there

**Comment by someone32** [comment]
No, it is not, I only have 1 drive, I managed to open it after reinstalling league, now every call I make, returns an empty response.

**Comment by someone32** [comment]
It was the drive! Fixed it! Thanks!

**Comment by ezx223** [comment]
I have Rift Explorer in D and it still not working

**Comment by Pupix** [comment]
A new version of Rift Explorer has been released to address some of the problems [v6.0.0](https://github.com/Pupix/rift-explorer/releases/tag/v6.0.0). Try it out and let me know if it's working for you.

**Comment by ezx223** [comment]
@Pupix This new version doesn't require enable_swagger in system.yaml? if not it's not working anyways it's the same "Waiting for league to start"

**Comment by Pupix** [comment]
No, you don't have to edit anything with the new version.
