### ISSUE TITLE
repair loop

### ISSUE THREAD

**Issue by specuuu** [Pupix/rift-explorer#39]
hi, how to fix it? I tried to move system.yaml to config directory and it didn't work. Nothing works.

**Comment by Pupix** [comment]
This is a known problem https://github.com/RiotGames/developer-relations/issues/117

Temporary workaround is here: https://github.com/Pupix/rift-explorer/issues/34#issuecomment-485089457

**Comment by specuuu** [comment]
I tried it and it didn't work.

**Comment by Pupix** [comment]
That's the only workaround that I know of. If it doesn't work for you then idk what to do. I'll look into finding other solutions for this and make another release.

**Comment by specuuu** [comment]
okay thanks, that bypass doesn't work anymore i guess.

**Comment by Pupix** [comment]
This has been fixed in [v6.0.0](https://github.com/Pupix/rift-explorer/releases/tag/v6.0.0). Try it out and let me know if it's working for you.

**Comment by specuuu** [comment]
Unfortunately my client is keep repairing. Do i still need to use enable_swagger: true?
