### ISSUE TITLE
How can i get password

### ISSUE THREAD

**Issue by ewranus** [Pupix/rift-explorer#4]
curl -X GET --header 'Accept: application/json' --header 'Authorization: Basic cmlvdDpqd2V3bVU4WmNZeGJYeHhlUk9MRWRB' 'https://localhost:50207/lol-login/v1/session'

How can i find "Authorization: Basic ??????" and port number

**Comment by lmachens** [comment]
Take a look at https://github.com/Pupix/rift-explorer/blob/48886c5817e0092fa7a5aa370ae3916a9503eb05/app/index.html#L50

**Comment by Pupix** [comment]
The values are present as process arguments and can also be found in a file in your League of Legends directory called `lockfile` that gets created when you start the client.

The file has the following format: 
```
LeagueClient:11616:50236:Y_L2o7ZRXvBekSDA6c8PEg:https
```
- port: 50236
- password: Y_L2o7ZRXvBekSDA6c8PEg

**Comment by elnath78** [comment]
> The values are present as process arguments and can also be found in a file in your League of Legends directory called `lockfile` that gets created when you start the client.
> 
> The file has the following format:
> 
> ```
> LeagueClient:11616:50236:Y_L2o7ZRXvBekSDA6c8PEg:https
> ```
> 

Is this data still correct? I tried that but both https://localhost:<port_numer>/liveclientdata/activeplayer and https://localhost:<port_number>/lol-login/v2/session return "Invalid URI format" Im trying on both Firefox and Chrome, but perhaps I'm missing something.

**Comment by LeOndaz** [comment]
For everyone who's still stuck in getting this working, see [this awesome article](https://nickcano.com/reversing-league-of-legends-client/)
