### ISSUE TITLE
Waiting for League to start...

### ISSUE THREAD

**Issue by Auona** [Pupix/rift-explorer#40]
rift-explorer-v3.0.0 version is ok, but rift-explorer-v5.0.0 version not ok.
both LOL and rift-explorer use admin right.

**Comment by Pupix** [comment]
Try the new version [v6.0.0](https://github.com/Pupix/rift-explorer/releases/tag/v6.0.0) and let me know if it's working for you.

**Comment by nylonW** [comment]
v6.02 same issue on macOS `Error: system.yaml not found`

**Comment by Pupix** [comment]
v6.0.2 only works if the new patcher is enabled. Do you have it?

**Comment by Auona** [comment]
I use v6.0.1 to test the latest LOL,it also not work, and I also use v3.0.0, it not work too. I think the latest LOL not  support?

**Comment by Pupix** [comment]
OS and region?

**Comment by Auona** [comment]
use windows 7 os, china province

**Comment by Pupix** [comment]
run
```
WMIC PROCESS WHERE name="LeagueClient.exe" GET ExecutablePath
``` in a terminal and post the result

**Comment by WildMaikeru** [comment]
i'm having the same issue, i can post the result for that
![11](https://user-images.githubusercontent.com/41396956/67152716-7ba37380-f291-11e9-8de8-2cc6c552aa20.png)

**Comment by RayZz-** [comment]
Closing as no response since October 20.
