### ISSUE TITLE
enabling swagger causes the game to stop working

### ISSUE THREAD

**Issue by Jeymej** [Pupix/rift-explorer#42]
The game no longer tries to repair the game files. When the rift explorer said that swagger was disabled I enabled it by putting enable_swagger: true in the system.yaml with the new patcher disabled and now the game won't even run, no sign, no process in the task manager no nothing.

**Comment by Jeymej** [comment]
And I ran everything as administartor all the time.

**Comment by Pupix** [comment]
What version of Rift Explorer are you using? During the past months a lot changed inside the League Client and some versions don't work anymore.

**Comment by Jeymej** [comment]
The latest one, 6.0.1.

**Comment by Pupix** [comment]
You don't need to edit anything with 6.0.1. Just open if after the client finished repairing, it will work as expected.

**Comment by Jeymej** [comment]
Can't load Swagger. Make sure it's enabled in system.yaml.

**Comment by Pupix** [comment]
The latest version doesn't have that message. It will just ask for a client restart to fix it. 
![image](https://user-images.githubusercontent.com/4929965/58051494-a2c70f00-7b52-11e9-8de8-b5416a18d239.png)

**Comment by Jeymej** [comment]
![Unefseftitled](https://user-images.githubusercontent.com/42285336/58051904-aeff9c00-7b53-11e9-84fb-0f7ea29c89e1.jpg)
![Untitl345345ed](https://user-images.githubusercontent.com/42285336/58051905-aeff9c00-7b53-11e9-971a-a1d961243257.jpg)

**Comment by Jeymej** [comment]
The 6.0.2 works fine, I think the issues is solved, I'll just try a few more times to make sure.

**Comment by Jeymej** [comment]
Oh, okay. Didn't know that the latest version resets the game automatically now, reseting the game manualy however causes this swagger issue but yet with the automatic reset it works just fine.
