### ISSUE TITLE
Please help me with rift-explorer.

### ISSUE THREAD

**Issue by hiimcupcake** [Pupix/rift-explorer#47]
Im on Garena but when i open up rift-explorer, it shows that the game is corrupted. then i reopen the game and it works normally but rift-explorer cant load swagger
https://imgur.com/a/uy6WSAk
https://imgur.com/a/BzMrINT

**Comment by hiimcupcake** [comment]
oh nevermind, i used the older version (5.0.0) and it works. thanks

**Comment by Pupix** [comment]
Yea Garena is kinda iffy because of the Garena launcher
