### ISSUE TITLE
game crashing after changing summoner icon

### ISSUE THREAD

**Issue by mwattew** [Pupix/rift-explorer#50]
game crashes randomly after changing the summoner icon and then it turns back into the starter icon from the tutorial.

**Comment by Pupix** [comment]
The icon reverting is a known issue. It will eventually stick if you keep changing it back.

What version are you using that's making the game crash? Never heard of this before.

**Comment by mwattew** [comment]
I'm using v6.0.2 also after playing around a bit I figured out that it closes my game as well when I close rift explorer after changing my summoner icon. 

a video in a zip: 
[2019-05-31 09-05-14.zip](https://github.com/Pupix/rift-explorer/files/3242042/2019-05-31.09-05-14.zip)

**Comment by Pupix** [comment]
That happens all the time, not just if you change the icon. This is a side effect of the workaround applied to the new league patcher.

**Comment by orange520** [comment]
I also caused the game to crash, and it would crash within 10 minutes of the game.

**Comment by RayZz-** [comment]
Please open a new issue with any appropriate logs rather than posting on a old and closed issue
