### ISSUE TITLE
How to listen to events?

### ISSUE THREAD

**Issue by Thyoity** [Pupix/rift-explorer#54]
Hi,

Awesome work on Rift Explorer!!!

I already can get the connected LoL accont in my Electron App.

I just noticed that I can connect to WebSocket server, I can make requests to the API and get resposes, but I can't listen to client events. How can I do that?

I'm currently using ``require('websocket').client`` package to handle the websocket part.
Everything is working fine, but the only problem is that the message callback is never being called, no matter what I do in my LoL client:

This is how my code looks right now:
![image](https://user-images.githubusercontent.com/10885945/59153022-bb766680-8a26-11e9-8ae7-b87e6b37e4d2.png)

Is there a specific protocol I should use, or a recommended WebSocket implementation? I just found a Gist written by you: https://gist.github.com/Pupix/eb662b1b784bb704a1390643738a8c15
Is this the current LoL client WS Protocol? (WAMP v1)
I'm not specifying this protocol in the WebSocket plugin I'm currently using, could this be the reason why I can't capture those client events?

Thankss in advance!!!

**Comment by Pupix** [comment]
You need to subscribe to events, otherwise the message handler won't fire.
Showed here https://gist.github.com/Pupix/eb662b1b784bb704a1390643738a8c15#file-index-js-L79

To get all the possible events you can look under the `/help` endpoint
