### ISSUE TITLE
traditional Chinese lang

### ISSUE THREAD

**Issue by be90728** [Pupix/rift-explorer#6]
'use strict';

/* jshint quotmark: double */
window.SwaggerTranslator.learn({
    "Warning: Deprecated":"警告：已過時",
    "Implementation Notes":"實現備註",
    "Response Class":"響應類",
    "Status":"狀態",
    "Parameters":"參數",
    "Parameter":"參數",
    "Value":"值",
    "Description":"描述",
    "Parameter Type":"參數類型",
    "Data Type":"數據類型",
    "Response Messages":"響應消息",
    "HTTP Status Code":"HTTP狀態碼",
    "Reason":"原因",
    "Response Model":"響應模組",
    "Request URL":"請求URL",
    "Response Body":"響應Body",
    "Response Code":"響應碼",
    "Response Headers":"響應Header",
    "Hide Response":"隱藏響應",
    "Headers":"Headers",
    "Try it out!":"試試看！",
    "Show/Hide":"顯示/隱藏",
    "List Operations":"顯示操作",
    "Expand Operations":"展開操作",
    "Raw":"原始",
    "can't parse JSON.  Raw result":"無法解析JSON. 原始結果",
    "Model Schema":"模型架構",
    "Model":"模組",
    "apply":"套用",
    "Username":"帳號",
    "Password":"密碼",
    "Terms of service":"服務條款",
    "Created by":"開發者",
    "See more at":"查看更多：",
    "Contact the developer":"聯繫開發者",
    "api version":"api版本",
    "Response Content Type":"響應Content Type",
    "fetching resource":"正在獲取資源",
    "fetching resource list":"正在獲取資源列表",
    "Explore":"瀏覽",
    "Show Swagger Petstore Example Apis":"顯示 Swagger Petstore 範例 Apis",
    "Can't read from server.  It may not have the appropriate access-control-origin settings.":"無法從服務器讀取。可能沒有正確設定access-control-origin。",
    "Please specify the protocol for":"請指定協定：",
    "Can't read swagger JSON from":"無法讀取swagger JSON於",
    "Finished Loading Resource Information. Rendering Swagger UI":"已加載資源訊息。正在處理Swagger UI",
    "Unable to read api":"無法讀取api",
    "from path":"從路徑",
    "server returned":"服務器返回"
});

**Comment by Pupix** [comment]
what's this exactly?

**Comment by be90728** [comment]
I see "rift-explorer-master\app\lang" is the folder, it is traditional Chinese, originally only zh-cn (Simplified Chinese)

**Comment by be90728** [comment]
Sorry, I do not know what PR is

**Comment by be90728** [comment]
PR? What does it mean, I'm only 16 yo lul

**Comment by Pupix** [comment]
A PR is a *Pull Request*. It allows you to contribute to other people's projects in a proper manner. https://help.github.com/articles/about-pull-requests/

**Comment by be90728** [comment]
Done!

**Comment by Pupix** [comment]
Nope. There's no PR.

![](https://i.imgur.com/w1R3PRT.png)

**Comment by be90728** [comment]
https://github.com/Pupix/rift-explorer/compare/master...be90728:patch-1

**Comment by Pupix** [comment]
Huh, must be the name change that's throwing it off. 🤷‍♂️ 

Can you try clicking the `New pull request` from [here](https://github.com/Pupix/rift-explorer/pulls) and try that way?

**Comment by Pupix** [comment]
Merged
