### ISSUE TITLE
League closes by itself

### ISSUE THREAD

**Issue by Ribathics** [Pupix/rift-explorer#68]
I think it's related to the new patch and it's happened before, but when I do all the procedures correctly the league client closes by itself and repairs.
I'm using the latest version (6.11);
Windows 7 64 bits;
Server: Brazil

**Comment by Pupix** [comment]
what procedures are you talking about?

**Comment by Ribathics** [comment]
I mean, in the past when I had issues opening it up it had to do with enable_swagger: true or I had to execute League and Riftexplorer as an admin, I'm not sure if it does the enable_swagger: true thing by itself now, but I tried both doing it and not doing it and executing as admin but neither worked.

**Comment by Pupix** [comment]
If you edit files the client will just restart and patch the files. You just need to start League and Rift Explorer, no editing anything.

**Comment by Ribathics** [comment]
I did both without editing and with editing to test out, neither worked.

**Comment by Pupix** [comment]
so which one is it then? It closes by itself or shows that message?

That message pops up because the LCU server doesn't start fast enough, meaning that you have too many programs opened and it struggles to start. Close some chrome tabs or other apps and try again.

**Comment by Kixej** [comment]
help me please
