### ISSUE TITLE
Waiting for League to start

### ISSUE THREAD

**Issue by xenu1** [Pupix/rift-explorer#70]
My league of legends is open but rift explorer does not recognize it. I've tried reinstalling league and it didn't help.

**Comment by Pupix** [comment]
Make sure they are both ran as admin. This happens because RE can't connect to League if it was started as admin.

**Comment by xenu1** [comment]
Tried that and that even didn't work D:

**Comment by Pupix** [comment]
region and os?

**Comment by xenu1** [comment]
Windows 10 1903 NA server

**Comment by Pupix** [comment]
what do you see if you run `WMIC PROCESS WHERE name="LeagueClient.exe" GET ExecutablePath` in a terminal?

**Comment by xenu1** [comment]
ERROR:
Description = The service cannot be started, either because it is disabled or because it has no enabled devices associated with it.

**Comment by Pupix** [comment]
That's the problem. You need WMIC to make RE work. As to why it doesn't work on your machine I have no idea. Maybe you are not an admin on your machine, maybe your installation is borked. If you manage to get the WMIC command to work, RE will work too.
