### ISSUE TITLE
Icons with number 100+

### ISSUE THREAD

**Issue by katkatkat456** [Pupix/rift-explorer#71]
How can i put a icon that is not Chinese on league of legends? The icons that have the number 100 and more not work.

**Comment by Pupix** [comment]
You can't. The chinese icons are already owned by you but not visible in the western clients. You can't use icons you don't own.

**Comment by katkatkat456** [comment]
ok.

**Comment by nicoberlaender** [comment]
Is there an available API call to see all icons a summoner owns?
