### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by Barbosicks** [Pupix/rift-explorer#74]
Rift Explorer no longer works with the new Riot login client. It always patches the system.yaml before launching the LeagueClient.exe.

**Comment by Pupix** [comment]
Yea I heard there are some problems with it on PBE and OCE. Don't know how much the launcher and LCU will change until the public launch so I am not gonna modify Rift Explorer as of yet. Once the new launcher goes public to everybody (including EUW, where I am) I will look into trying to fix RE.

**Comment by Barbosicks** [comment]
Cool! Glad to hear.
The Riot login client itself has a swagger API too so maybe we can have rift explorer for that too? Just an idea for the future.

**Comment by officialkl** [comment]
Working but when the game is over, the previous icon is returned causing me to use the program again with each game over! The summoners profile wallpaper was perfect, just the 29 icon profile ''no icon'' need restart a rift explorer to make again every game!
