### ISSUE TITLE
Can't load swagger

### ISSUE THREAD

**Issue by gms122** [Pupix/rift-explorer#78]
i just got Can't load Swagger. Make sure it's enabled in system.yaml this error in rift explorer when i launc league of legends. Really want to change the icon but dont really know how to fix this issue

**Comment by RayZz-** [comment]
Are you using the latest version `V6.1.1`.
Also whats's your OS and region

**Comment by gms122** [comment]
Yes, im using latest version on windows 10 and my region is EUW

**Comment by Pupix** [comment]
Make sure the directory where league is installed is not read-only.
