### ISSUE TITLE
URL to send chat message in champ select ?

### ISSUE THREAD

**Issue by Marbellasaad** [Pupix/rift-explorer#8]
Hi,

Firstly thanks you for Rift-Explorer and LCU connector

I try to search but i can't find where is the api url to send message in champ select,would you have it ?

Thanks

**Comment by Pupix** [comment]
You can send messages in champ select just like you send private messages, with `lol-chat` endpoints. If you list if conversations you got going you will find a chat room with `type: championSelect`.

**Comment by Marbellasaad** [comment]
Hi,thanks you for the help that worked,just one more question how can we know the id for this action : http://prntscr.com/hw2nk8

The session url doesn't return an id

**Comment by Pupix** [comment]
🤷‍♂️
