### ISSUE TITLE
Waiting for league to start...

### ISSUE THREAD

**Issue by cansador** [Pupix/rift-explorer#81]
only appears this msg "waiting for league to start.." tried already download old versions for see if works but didnt, tried to exec as adminstrator still didnt work, help. :(

**Comment by Pupix** [comment]
run
```
WMIC PROCESS WHERE name="LeagueClient.exe" GET ExecutablePath
``` in a terminal and post the result

**Comment by RayZz-** [comment]
Closing as not response from OP since September 14.
