### ISSUE TITLE
Support for Riot-Client?

### ISSUE THREAD

**Issue by NoTeefy** [Pupix/rift-explorer#85]
Can we expect proper support for the new riot client/launcher in future releases?
Just bypassing it by disabling it isn't the best and future-proof solution...

**Comment by Pupix** [comment]
It's not a proper solution indeed. The client hasn't even been globally released so I won't touch it until that happens because Riot has a tendency to change stuff wildly.

Once the Riot Client hits GA I will look into a proper solution.
