### ISSUE TITLE
How to install dependencies

### ISSUE THREAD

**Issue by GGPeridot** [Pupix/rift-explorer#87]
I am trying to build a 32bit version, but I don't know how to install dependencies like the readme.md said me

**Comment by RayZz-** [comment]
nodejs needs to be installed on the system then you need to go to the directory using the commandline and run `npm start`

**Comment by GGPeridot** [comment]
thanks!

**Comment by RayZz-** [comment]
sorry you would need to run `npm install` then either run `npm start` to start it or `npm run build` to build the binaries

**Comment by GGPeridot** [comment]
oh alright then
