### ISSUE TITLE
dosnt works

### ISSUE THREAD

**Issue by yetoria** [Pupix/rift-explorer#89]
hi, when it will works it keeps saying " need to restart to work properly "

**Comment by RayZz-** [comment]
Any error logs? just saying "doesn't work" doesn't help

**Comment by yetoria** [comment]
" Rift explorer needs to restart your League of Legends client to work properly " then my client restarts and updates and then the message repeats itself

**Comment by leonardo9717** [comment]
Run rift-explorer as Admin, works for me.

**Comment by yetoria** [comment]
Yes i do too but idk it dont works, it keeps restarts the client

**Comment by RayZz-** [comment]
We are expecting a fix soon but for now i'm going to close this issue.
