### ISSUE TITLE
Not Working on the PBE

### ISSUE THREAD

**Issue by artem1919** [Pupix/rift-explorer#9]
With the recent PBE update, it no longer works. It will probably stop working on the live servers too once the next update comes.

I am getting stuck with the "Waiting for League to start..." message.

**Comment by Pupix** [comment]
Seems that CEF doesn't handle authentication through URL anymore. Fixed in [v1.0.2](https://github.com/Pupix/rift-explorer/releases/tag/v1.0.2)
