### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by AISWolf** [Pupix/rift-explorer#92]
Hey when I tried today to download Rift explorer and writing down that swagger stuff and then trying to start the Rift explorer program it ended as an error. The error message said, "Rift Explorer needs to restart your League Of Legends client to work properly". This message got spammed and my client just restarted the whole time. I have redownloaded the version and nothing changed. I also restarted my computer and nothing worked. I also started the program as an Administrator. And lastly, i play on EUW. Can you by any chance help me? But when this popup error comes up the program is still loading and I can scroll around. But when it comes to writing down a command the whole program just freezes. Pls help

**Comment by AISWolf** [comment]
Nevermind I have find a solution. You need to start league and then restart it by pressing ok on the error. Then you log in and instead of clicking on the error again you just ignore it. Now let riftexplorer load and you can use it. I changed my icon to nothing but NOTE don't copy paste because thats gonna crash the program. Just write everything with your Keyboard.

**Comment by yetoria** [comment]
what is your ign? can you help me? it doesnt works for me

**Comment by AISWolf** [comment]
Well whats ur problem? I can try to help

**Comment by RayZz-** [comment]
Hopefully this will be resolved in a new version soon. Closing this one for now if this does persist in the new version please don't hesitate to reopen this issue.
