### ISSUE TITLE
Can't load Swagger. Make sure it's enabled in system.yaml

### ISSUE THREAD

**Issue by IakovosD** [Pupix/rift-explorer#95]
There is no 
enable_swagger: (true/false)
on system.yaml

What should i do, because the rift explorer wont open with the error "Can't load Swagger. Make sure it's enabled in system.yaml"...

**Comment by RayZz-** [comment]
Rift explorer does that for you. but the issue here is know and hopefully a new fix will be out soon which should fix this issue.
