### ISSUE TITLE
Does not work (Waiting for League to start) and Press here to restart league

### ISSUE THREAD

**Issue by arrasdev** [Pupix/rift-explorer#98]
I have both rift explorer and LoL running in admin mode, but RIft Explorer keeps on asking me to restart the client with a dialogue box. I click that and it says the same thing over and over even after it restarts.

**Comment by liflovs** [comment]
+1

**Comment by DemoXinMC** [comment]
I've also run into this issue, but have not tried building myself, only using the pre-built binaries on 9.24

**Comment by TLHaruXXX** [comment]
+1

**Comment by liflovs** [comment]
Actually it does work but only after sign in if you ignore the popup you can use app somehow

**Comment by RayZz-** [comment]
This issue will hopefully be resolved in a future update. Closing this for now if the issue still persists the please reopen this issue.
